### ISSUE TITLE
The method addSpecRef is missing in index.d.ts

### ISSUE THREAD

**Issue by tansin** [seriousme/openapi-schema-validator#113]
Hello and thanks for this useful piece of software!

I'm using the version 2.1.1 in a typescript project. The method addSpecRef is missing in index.d.ts though, so that the typescript compiler complains.

**Comment by seriousme** [comment]
Hi,

Thanks for submitting the issue !
Its indeed missing and I also noticed that there was an error in https://github.com/seriousme/openapi-schema-validator/blob/master/README.md#api where the parameters were swapped :-(

A PR to fix both items will follow soon.

Kind regards,
Hans

**Comment by seriousme** [comment]
Released as version 2.1.2 on NPM. Hope this helps !

**Comment by tansin** [comment]
> Released as version 2.1.2 on NPM. Hope this helps !

Thanks a lot!
