### ISSUE TITLE
Cannot perform validation in strict mode

### ISSUE THREAD

**Issue by Belrestro** [seriousme/openapi-schema-validator#14]
Using version `1.1.3`, I was trying to validate schema using strict mode. It seems so that feature not supported, or in some was is not compatible.

As soon as strict mode enabled fails with error:

```Error: unknown format "uri" ignored in schema at path "#/properties/url"```
I think error refers not schema I validate but rather different schema
`https://json-schema.org/draft/2020-12/schema`
or
`https://spec.openapis.org/oas/3.1/schema/2021-05-20`
not sure.

**Comment by Belrestro** [comment]
I've tried to run tests featured in project, but rather initiating `Validator` instance with empty object in `test-validation.js` file, and it fails in multiple cases.

**Comment by seriousme** [comment]
hi,

AJVs Strict Mode is not compatible with the Openapi Specifications.
No Strict Mode however does not impact validation.

Kind regards,
Hans

**Comment by seriousme** [comment]
BTW the tests work in CI on Ubuntu Linux
did you run: 
- npm install
- npm test

**Comment by Belrestro** [comment]
> AJVs Strict Mode is not compatible with the Openapi Specifications.
That's a pity.

That, I did modified test to:
> I initiated `Validator` instance with empty object
Which I suppose it sets strict mode to `true`.

**Comment by seriousme** [comment]
I overlooked the "empty object", sorry for that.

If you pass an empty object then you override the default settings, see https://github.com/seriousme/openapi-schema-validator/blob/392b7ae7127a844064d0ce02a71168ebc3cb99d7/index.js#L49

So you can play with the AJV options, but it is not recommended ;-)
AJV "Strict mode" applies rather rigourous linting and the OpenAPI specs use quite advanced JSON schema.
I checked with the  openApi maintainers and they concluded that AJV strict mode was too strict.

You could apply:
```javascript
{ strict: "log", validateFormats: false }
```
 To get the warnings logged , see https://ajv.js.org/strict-mode.html

Kind regards,
Hans

**Comment by seriousme** [comment]
FYI: just published 1.1.4 on NPM that also solves the empty object case and has improved documentation.
Thanks for reporting this !

Hans

**Comment by Belrestro** [comment]
That is great, thank you !
