### ISSUE TITLE
$ref to other files

### ISSUE THREAD

**Issue by GuillaumeDeconinck** [seriousme/openapi-schema-validator#34]
Hello !

First thank you for this project and fastify-openapi-glue, it really helps for implementing a documentation-first API 🙂 

I'm currently trying to use `fastify-openapi-glue` with an OpenAPI definition splitted in multiple files. From what I saw, it raises an error in this package.

If I understand correctly, this package doesn't retrieve the other files and thus I should provide a self-contained definition file ?
Or did I miss something ? 🙂

Just to give all the infos, I'm using the syntax for getting other files like that:
```yaml
# OpenAPI file
# [...]
paths:
  /todos:
    $ref: "./list_todos.yaml"
```
And it fails in https://github.com/seriousme/openapi-schema-validator/blob/master/resolve.js#L33 as there is no `#` character in the uri, which gives the error `Cannot read property 'length' of undefined`.

Thanks in advance for the input

**Comment by GuillaumeDeconinck** [comment]
My bad, missed that part in the readme, thanks for the info and the clearer error message :)

Kinds regards

**Comment by GuillaumeDeconinck** [comment]
Hans,

I've looked a bit at the branch, it looks good and it can definitely help 😉 

I have a few questions/suggestions. I'm aware that it's a small update to add some functionality to aid my use case, and therefore, it's of course not a big new feature. But I'm not sure of all the implications of this small change, so I prefer to ask:

Is the `#` still mandatory in the `$ref` value ?
In my case, in the URIs, there is often no "JSON pointer", so the whole sub-spec should be used. I haven't looked yet in the lib how it works, so maybe my question is stupid.

However, seeing that the sub-specs have to be explicitly specified, I was wondering:
I guess, ideally, the lib could infer and pull the sub-specs directly (based on the possibilities specified in the [Openapi specs](https://swagger.io/docs/specification/using-ref/)). For example, in my case, I have like 20-30 sub-specs, so that would make a lot of calls to `addSpecRef`. On the other hand, having a lot of files to load from disk (or worse, a lot of files to be pulled from the web) takes some time, so note that the argument of having one "self-contained spec" still somehow holds, as it doesn't worsen too much the start time of an app.

What do you think about this ? I know this is a lot more work, and I don't expect you to do it at all. I'm actually interested to know your opinion on the matter.
In fact, if you need help on that, I can try to do a PR 😉 
In all cases, thanks for the input and the current improvements, it's already a big timesaver !

Kind regards,
Guillaume

**Comment by GuillaumeDeconinck** [comment]
Hans,

Thanks ! I'll try your branch and use `addSpecRef` in my project today or tomorrow 😉 (was planning do to it anyway)

Ahah you're right, I went indeed a little overboard about the load time of fetching all the local files, as you say the NPM ecosystem is already infamous for doing this and it isn't an issue.

I totally agree about the whole "fetching data/specs from external/third party sources doesn't really bring confidence". I wouldn't have a production workload do this kind of critical lookups either. I meant it more like "being full compatible with swagger/openapi specs", but this is indeed a good reason to not include this. Moreover, as you said, `addSpecRef` covers everything if some preprocessing is done in order to fetch the sub-specs 🙂 

Thanks for the answer !

Kinds regards,
Guillaume

**Comment by seriousme** [comment]
Btw:  AJV uses the same strategy as I do: https://ajv.js.org/faq.html#generating-schemas-with-resolved-references-ref
Adding schemas is possible by using https://ajv.js.org/api.html#ajv-addschema-schema-object-object-key-string-ajv

Based on this I have added the option to add a `$id` attribute in the subspec and reversed the parameters of `addSpecRef`.

Kind regards,
Hans

**Comment by seriousme** [comment]
Published as 1.6.0 on NPM

Thanks again !
Hans

**Comment by mzbik** [comment]
I was able to get this working as well in my project. However, it is unfortunate that the way that I choose to factor my openapi docs is also surfaced in the code.  For example, I currently have types.yaml that contains shared schema and my code has me doing addSpec for '../common/types.yaml'.  If I choose to split this file and edit any relevant .yamls , I now need to go and edit the code as well.

It would sure be nice to have a way to hide my factoring choices in openspec layouts from the code.

**Comment by seriousme** [comment]
@mzbik thanks for asking.
An easy way out might be to have your code add all .yamls automatically, or use  a separate build script that generates an import from your source tree.

Hope this helps.

Kind regards,
Hans

**Comment by mzbik** [comment]
Both solutions still surface factoring decisions in yaml layout in code: change the layout => change the code.  The solution is to take a single top-level specification, look for #ref, add those yamls with the correct relative path, rinse/repeat until no more additions.

**Comment by seriousme** [comment]
The OpenAPI spec defines $refs as URI's (Uniform Resource Identifier) and *not*  as URL's (Uniform Resource Locators).
(see https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#reference-object)

So although on the surface it looks like a URL it actually is a URI, and you can put in anything that is allowed as URI.
So `$ref: urn:oasis:names:specification:docbook:dtd:xml:4.1.2`  is also a valid URI although it does not say anything about the file's location.

Kind regards,
Hans

**Comment by mzbik** [comment]
The subsection on [Relative References in URIs](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#relative-references-in-uris)  seems to indicate that relative references are processed relative to the base document via [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-5.2).

I hate reading/interpreting RFC's...

Cheers!

**Comment by seriousme** [comment]
Correct, so if the $id of the basedocument is `http://a/b/c/d;p?q` then  `$ref:g` means: look for a document with `$id: http://a/b/c/g`.  It does not mean:  go to `http:/a`  and fetch `/b/c/g`.
That is the difference between `Identifier` and `Locator`. Its perfectly fine to have a file called `spec.json` containing `$id: main.json` or `main` or `main.xml` etc..

Hence assuming that the URI designates a URL might sound convenient but can also lead to unwanted surprises.

Kind regards,
Hans
