### ISSUE TITLE
The default export was removed from index, cli not updated

### ISSUE THREAD

**Issue by tbcarver** [seriousme/openapi-schema-validator#64]
![image](https://user-images.githubusercontent.com/86443400/165557379-68bd6618-4ca0-4790-87e4-b404657c7ba4.png)

Fixed in PR: https://github.com/seriousme/openapi-schema-validator/pull/63

**Comment by seriousme** [comment]
Released as [2.0.1](https://github.com/seriousme/openapi-schema-validator/releases/tag/v2.0.1)

Thanks again,
Hans

**Comment by tbcarver** [comment]
👍 any time, great project!
